version: '3.9'
services:
  web:
    container_name: worksight_web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - apps/web/.env.example
    restart: unless-stopped

  docs:
    container_name: worksight_docs
    build:
      context: .
      dockerfile: apps/docs/Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: sgsite-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - docs

