name: Build & Publish Docs

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/docs/**'
      - '.github/workflows/build-docs.yml'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter apps/docs lint

      - name: Test
        run: pnpm --filter apps/docs test --if-present

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/docs:latest ./apps/docs

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/docs:latest
