name: Deploy to Vercel and GitHub Pages

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'
  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
  NEXT_PUBLIC_DEV_URL: ${{ vars.NEXT_PUBLIC_DEV_URL }}
  NEXT_PUBLIC_IS_OFFLINE: ${{ vars.NEXT_PUBLIC_IS_OFFLINE || 'false' }}
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
  IS_OFFLINE: ${{ vars.IS_OFFLINE || 'false' }}


jobs:
  deploy-web:
    name: Deploy Web to Vercel
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⬇️ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.1 # Keep your pnpm version consistent

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Change this line to '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter=@worksight/web
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --cwd=apps/web
